-- REMOVE: Copper Modulator From NPC_TRAINER (48 DB ERRORS FIXED)
DELETE FROM npc_trainer WHERE spell=3926;

-- REMOVE: Shield Bash From NPC_TRAINER (50 DB ERRORS FIXED)
DELETE FROM npc_trainer WHERE spell=72;

-- REMOVE: Sense Demons From NPC_TRAINER (6 DB ERRORS FIXED)
DELETE FROM npc_trainer WHERE spell=5500;

#FIXED BY ARIDEV